In [2]:
import numpy as np
import pandas as pd
df = pd.DataFrame(
    {
        "A":[1, np.nan, 3, 4, 5],
        "B":[6, 7, 8, np.nan, 10],
        "C":[11, 12, 13, 14, 15]
    }
)
df

     A     B   C
0  1.0   6.0  11
1  NaN   7.0  12
2  3.0   8.0  13
3  4.0   NaN  14
4  5.0  10.0  15

In [3]:
df.isnull()

       A      B      C
0  False  False  False
1   True  False  False
2  False  False  False
3  False   True  False
4  False  False  False

In [4]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy="mean")

imp.fit(df)
imp.transform(df)

ImportError: DLL load failed while importing _ufuncs_cxx: アプリケーション制御ポリシーによってこのファイルがブロックされました。

In [8]:
import pandas as pd
df = pd.DataFrame(
    {
        "A":[1, 2, 3, 4, 5],
        "B": ["a", "b", "a", "b", "c"]
             }
)
df

   A  B
0  1  a
1  2  b
2  3  a
3  4  b
4  5  c